/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanhVienRouteImport } from './routes/thanh-vien'
import { Route as SuKienRouteImport } from './routes/su-kien'
import { Route as PhanTichRouteImport } from './routes/phan-tich'
import { Route as IndexRouteImport } from './routes/index'

const ThanhVienRoute = ThanhVienRouteImport.update({
  id: '/thanh-vien',
  path: '/thanh-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const SuKienRoute = SuKienRouteImport.update({
  id: '/su-kien',
  path: '/su-kien',
  getParentRoute: () => rootRouteImport,
} as any)
const PhanTichRoute = PhanTichRouteImport.update({
  id: '/phan-tich',
  path: '/phan-tich',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/phan-tich': typeof PhanTichRoute
  '/su-kien': typeof SuKienRoute
  '/thanh-vien': typeof ThanhVienRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/phan-tich': typeof PhanTichRoute
  '/su-kien': typeof SuKienRoute
  '/thanh-vien': typeof ThanhVienRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/phan-tich': typeof PhanTichRoute
  '/su-kien': typeof SuKienRoute
  '/thanh-vien': typeof ThanhVienRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/phan-tich' | '/su-kien' | '/thanh-vien'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/phan-tich' | '/su-kien' | '/thanh-vien'
  id: '__root__' | '/' | '/phan-tich' | '/su-kien' | '/thanh-vien'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhanTichRoute: typeof PhanTichRoute
  SuKienRoute: typeof SuKienRoute
  ThanhVienRoute: typeof ThanhVienRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanh-vien': {
      id: '/thanh-vien'
      path: '/thanh-vien'
      fullPath: '/thanh-vien'
      preLoaderRoute: typeof ThanhVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/su-kien': {
      id: '/su-kien'
      path: '/su-kien'
      fullPath: '/su-kien'
      preLoaderRoute: typeof SuKienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phan-tich': {
      id: '/phan-tich'
      path: '/phan-tich'
      fullPath: '/phan-tich'
      preLoaderRoute: typeof PhanTichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhanTichRoute: PhanTichRoute,
  SuKienRoute: SuKienRoute,
  ThanhVienRoute: ThanhVienRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
